# Generated by Django 4.1.3 on 2022-12-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
