# Generated by Django 4.1.3 on 2022-12-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser2', '0002_remove_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='published_data',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
